### ISSUE TITLE
启动程序自动弹出谷歌浏览器访客模式

### ISSUE THREAD

**Issue by Mrdyzjgd** [succInf/yuqueDocumentDoloader#1]
启动程序之后，会自动弹出浏览器访客模式，访问语雀地址要重新登录账号密码，导致运行失败。
![WX20240918-114418@2x](https://github.com/user-attachments/assets/22b82f53-feab-496d-903f-bc7c332b194b)

**Comment by v18268185209** [comment]
代码已更新 请参考cookies部分。
